### ISSUE TITLE
Continuous gallery

### ISSUE THREAD

**Issue by danieliust** [jsor/lity#11]
Hello,
Is it possible to create a continuous gallery, so once you open one image you could navigate back and forth (with the navigation arrows) to the next one without having to close the current one and open the next one manually?

Lity is fantastic and that's the only issue I need to solve to finish my project.
Please help me.

**Comment by jsor** [comment]
No, sorry. That is out of the scope of lity.

**Comment by danieliust** [comment]
What a pity... :(

**Comment by jsor** [comment]
There are a lot of great gallery libraries out there, eg. [PhotoSwipe](http://photoswipe.com).

**Comment by danieliust** [comment]
Yeah, but it doesn't support inline content... Any chances you could implement it? I could pay for it :)

**Comment by jsor** [comment]
> Yeah, but it doesn't support inline content...

Sure, it does: http://photoswipe.com/documentation/getting-started.html#dom-to-slide-objects

> Any chances you could implement it? I could pay for it :)

Nope, sorry :)

**Comment by hyperking** [comment]
@jsor I would like to take a fork and add this functionality. shame that it's not included. :-)

**Comment by C99nl** [comment]
@hyperking It'd be awesome if you could build that in.

**Comment by hyperking** [comment]
@C99nl yeah. It would be although I'm not the author of this plugin so polishing up the code base would have to be approved by @jsor.

My branch on this project has the gallery hardcoded to add navigation buttons and actions. you could grok some of the code you need to make it happen. I implemented it on a project seen [here](http://staging.exploremitchelville.org/archives/gallery/historic-mitchelville)

I only used lity because like a majority of us..I'm lazy

**Comment by Studioartcz** [comment]
What about PR @hyperking?

**Comment by hyperking** [comment]
@Studioartcz I'm not sure how that works when the repo belongs to someone else.

@jsor Is it ok for me to open a public repo for lity that has this specific functionality?

**Comment by jsor** [comment]
@hyperking Sure, Lity is MIT licensed. Feel free to fork and extend it.
