### ISSUE TITLE
Loaded twice image

### ISSUE THREAD

**Issue by krugerdavid** [jsor/lity#166]
Using Lity - v3.0.0-dev - 2017-07-17 when you click on the link for the lity lightbox to open, it added the same <div class="lity lity-opened lity-image">...</div> twice. Using v2.2.2 it works fine.

**Comment by jsor** [comment]
I cannot reproduce this. Could you setup a reproducible test case?

**Comment by stefanfmeyer** [comment]
BUMP - I have this issue too. Same issue where the lightbox is firing twice. Please advise

**Comment by hegemanjr** [comment]
This just happened to me. I am attempting to use Lity in a WordPress plugin, and I have come to realize that it is because it already being loaded by another plugin (Modern Events Calendar).

When I started development on the plugin, I had very few other plugins installed. I had installed plugins and added some content, then gone back to development on my plugin. This is when I noticed it was firing twice.

I'll have to figure out a way to gracefully make sure it only gets loaded once. I'll try to come back here if I find a good solution, but hopefully this helps sombody.

**Comment by hegemanjr** [comment]
Okay, I'm not sure how graceful it is, but it works. 

Recon:

- I found the culprit was Modern Events Calendar by searching for the "lity-hide" CSS class.
- I then found where they were enqueuing the script by searching for "lity.js" and "lity.min.js" to reveal the handle "mec-lity-script"

Solution:
Using the WP function [wp_script_is](https://developer.wordpress.org/reference/functions/wp_script_is/), I am checking to see if the "mec-lity-script" is enqueued before enqueuing it myself. This is admittedly a clunky solution, but it works and will have to do until I have more time to invest in it. If another theme or plugin includes it, I'll have to go through this again and add the culprit's handle to the condition.

```
add_action( 'wp_enqueue_scripts',function(){
	// Lightbox "Lity"
	if ( ! wp_script_is( 'mec-lity-script', 'enqueued' ) ) {
		wp_enqueue_style( 'lity-style', plugin_dir_url( __FILE__ ) . 'vendor/lity-2.4.1/dist/lity.css' );
		wp_enqueue_script('lity-script', plugin_dir_url( __FILE__ ) . 'vendor/lity-2.4.1/dist/lity.js' , array( 'jquery' ) );
	}
});
```
