### ISSUE TITLE
Youtube parameter (start at....)

### ISSUE THREAD

**Issue by braderz31** [jsor/lity#171]
Hi - I'm unable to get a Youtube video to start in the lightbox from a specific number of seconds.

It seems adding the "=10s" parameter to the end of Youtube URLs is ignored by the plugin.

I've tried using the share URL, Embed URL and Video page URL from YouTube.

Any ideas please?
Thanks

**Comment by jsor** [comment]
This has been answered a few times already, see eg. #75.

**Comment by iskrisis** [comment]
@jsor i don't think this is true for the 2.x branch.

https://github.com/jsor/lity/blob/v2.3.1/src/lity.js#L215 

This line that gets parameters that are already in url logs actually 
```
{?start: "178s"}
``` 
instead of 
```
{start: "178s"}
```
So the resulting url then ends up being &%3Fstart= (? gets url encoded) instead of &start=

This doesn't seem to be the issue for 3.dev branch. I am not sure whats causing this and i am a bit worried to use 3 dev version but there is probably some regex problem and i am just running away and gonna use version 3.
