### ISSUE TITLE
Youtube button doesn't show on firefox

### ISSUE THREAD

**Issue by davidmanson** [jsor/lity#28]
Hi and thank you for your work.

I'm facing a problem using your plugin to show youtube videos in firefox, the control buttons doesn't show up.
I noticed the problem exist in the official demo page : http://sorgalla.com/lity/

Thank you.

ps : firefox on OSX 10.11

**Comment by jsor** [comment]
Thanks for the report. This hasn't been an issue with Lity directly, but it seems the controls are missing if the embed url uses http instead of https.

I fixed it in Lity (b97c140b1542a2e7fb7a6265169751b3c537b1be) to always load iframe embeds with https ([v1.6.3](https://github.com/jsor/lity/releases/tag/v1.6.3)).

**Comment by davidmanson** [comment]
Thank you ! amazing support :)
