### ISSUE TITLE
programatically open?

### ISSUE THREAD

**Issue by andrewmartin** [jsor/lity#54]
Sorry if this was obvious; I dug around the source for a bit but didn't see anything obvious. Is there a way to programatically open the lightbox?

I'm doing a hacky solution that works:

```js
$('[data-lity]').trigger('click');
```

Just curious if there was a way to invoke a specific instance; and if so, is it in the docs anywhere?

**Comment by jsor** [comment]
No, there's no other way at the moment. That's the only and "correct" way.

**Comment by axeff** [comment]
I'm having a different approach where I would actually need the same thing with using inline content. So I have my div like this:
`<div class="lity-hide"><!-- js-video-player is in here --></div`
and I need to open lity with no data-lity attribute because it will be triggered from js. I could do a workaround like @andrewmartin but that seems nasty. Would be cool to have a way to open lity manually

**Comment by jsor** [comment]
See https://github.com/jsor/lity#programmatic

```html
<div class="lity-hide" id="video"><!-- js-video-player is in here --></div>
```

```js
var lightbox = lity();
lightbox('#video');
```

**Comment by axeff** [comment]
I only tried lity('#video'). Awesome, thx!

**Comment by jsor** [comment]
> I only tried lity('#video'). Awesome, thx!

Yes, that's a little flaw in the API which i'm going to correct in 2.0. `lity('#video')` will work then.
